# Generated by Django 4.0.4 on 2022-05-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('GPA', models.FloatField()),
                ('level', models.IntegerField()),
                ('mail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('dep', models.CharField(blank=True, max_length=2)),
                ('Gender', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('birth', models.DateField()),
            ],
        ),
    ]
